include(CMakeForceCompiler)

# set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;S;asm)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_ASM_COMPILER dpu-clang)
set(CMAKE_C_COMPILER dpu-clang)
set(CMAKE_CXX_COMPILER dpu-clang)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
